name: Build, Test and Pack NuGet Package
on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run xUnit Tests
        run: dotnet test Q3CSharpLib.Tests/Q3CSharpLib.Tests.csproj --no-build --configuration Release --verbosity normal

      # only pack and upload artifacts on Windows build
      - name: Pack NuGet package
        if: matrix.os == 'windows-latest'
        run: dotnet pack --no-build --configuration Release --output ./nupkgs

      - name: Store artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ./nupkgs/*.nupkg
